FROM plugins/base:multiarch

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone NPM" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

RUN apk add --no-cache git nodejs nodejs-npm

ADD release/linux/i386/drone-npm /bin/
ENTRYPOINT ["/bin/drone-npm"]
