FROM microsoft/nanoserver:latest
MAINTAINER Drone.IO Community <drone-dev@googlegroups.com>

ENV GODEBUG=netdns=go

# TODO: install nodejs and git

LABEL org.label-schema.version=latest
LABEL org.label-schema.vcs-url="https://github.com/drone-plugins/drone-npm.git"
LABEL org.label-schema.name="Drone NPM"
LABEL org.label-schema.vendor="Drone.IO Community"
LABEL org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-npm /bin/
ENTRYPOINT [ "/bin/drone-npm" ]
