FROM plugins/base:linux-arm

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone NPM" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

RUN apk add --no-cache git nodejs npm

ADD release/linux/arm/drone-npm /bin/
ENTRYPOINT [ "/bin/drone-npm" ]
