# escape=`
FROM plugins/base:windows-1809

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone NPM" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

# TODO: install required tools

ADD release\drone-npm.exe c:\drone-npm.exe
ENTRYPOINT [ "c:\\drone-npm.exe" ]
